spring:
  profiles:
    active: dev
---
# Server Setting
server:
  port: 8080
  servlet:
    context-path: /zaria
# Spring properties
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zaria?characterEncoding=utf8
    username: root
    password: 123456
    # 数据源
    type: com.alibaba.druid.pool.DruidDataSource
  # static
  mvc:
    static-path-pattern: /static/**
# Mybatis
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

# Logging

---
